version: '3'

volumes:
    deps:

services:
    app:
        image: node:10
        volumes:
            - .:/usr/src/app
            - deps:/usr/src/app/node_modules
        working_dir: /usr/src/app
        command: npm run gulp
